/** 常用参数名 → 中文显示名 */
export const ARG_NAMES: Record<string, string> = {
  limit: "数量",
  page: "页码",
  query: "搜索词",
  keyword: "关键词",
  username: "用户名",
  id: "ID",
  uid: "用户 ID",
  url: "链接",
  output: "输出路径",
  text: "内容",
  type: "类型",
  lang: "语言",
  sort: "排序",
  status: "状态",
  start_date: "开始日期",
  end_date: "结束日期",
  title: "标题",
  name: "名称",
  image: "图片",
  model: "模型",
  prompt: "提示词",
  timeout: "超时(秒)",
  index: "序号",
  symbol: "股票代码",
  "no-download": "不下载",
  quality: "画质",
  bvid: "BV号",
  "note-id": "笔记 ID",
  "post-id": "帖子 ID",
  "job-id": "任务 ID",
  "model-name": "模型名",
  "dept-id": "部门 ID",
  dept_id: "部门 ID",
  "download-images": "下载图片",
  max: "最大数量",
  size: "大小",
  format: "格式",
  path: "路径",
  file: "文件",
  dir: "目录",
  token: "令牌",
  key: "密钥",
  secret: "密钥",
  channel: "频道",
  topic: "话题",
  tag: "标签",
  category: "分类",
  region: "地区",
  country: "国家",
  date: "日期",
  time: "时间",
  from: "起始",
  to: "结束",
  offset: "偏移",
  count: "数量",
  num: "数量",
  mode: "模式",
  level: "等级",
  depth: "深度",
  width: "宽度",
  height: "高度",
  color: "颜色",
  theme: "主题",
  version: "版本",
  env: "环境",
  host: "主机",
  port: "端口",
  message: "消息",
  content: "内容",
  body: "正文",
  subject: "主题",
  email: "邮箱",
  phone: "手机号",
  password: "密码",
  token_type: "令牌类型",
};

export function getArgName(name: string): { cn: string | null; en: string } {
  const cn = ARG_NAMES[name] ?? ARG_NAMES[name.replace(/-/g, "_")] ?? null;
  return { cn, en: name };
}
