export const SITE_NAMES: Record<string, string> = {
  bilibili: "哔哩哔哩",
  zhihu: "知乎",
  xiaohongshu: "小红书",
  weibo: "微博",
  douyin: "抖音",
  wechat: "微信",
  qqmusic: "QQ音乐",
  netease: "网易云音乐",
  neteasemusic: "网易云音乐",
  douban: "豆瓣",
  v2ex: "V2EX",
  baidu: "百度",
  taobao: "淘宝",
  jd: "京东",
  pinduoduo: "拼多多",
  twitter: "Twitter / X",
  x: "Twitter / X",
  youtube: "YouTube",
  reddit: "Reddit",
  github: "GitHub",
  discord: "Discord",
  slack: "Slack",
  notion: "Notion",
  obsidian: "Obsidian",
  readwise: "Readwise",
  cursor: "Cursor IDE",
  telegram: "Telegram",
  instagram: "Instagram",
  facebook: "Facebook",
  linkedin: "LinkedIn",
  hackernews: "Hacker News",
  producthunt: "Product Hunt",
  medium: "Medium",
  substack: "Substack",
  _shared: "通用",
  antigravity: "Antigravity",
};

export function getSiteName(site: string): string {
  return SITE_NAMES[site.toLowerCase()] ?? site;
}
